### ISSUE TITLE
Integration with fragile v0.0.44

### ISSUE THREAD

**Issue by Guillemdb** [justindujardin/mathy#36]
Something came up and I cannot make the PR till at least Monday, but here you have a gist with the code to get rid of plangym as a dependence.

I didn't have time to test is properly but I am 95% sure it should work. If it doesn't please write me here and I will help you fix it.

https://gist.github.com/Guillemdb/405b03f4dd885b0f46018f0f190df6f9

**Comment by justindujardin** [comment]
Thanks for the gist example! Based on it I was able to get the new style code working without a plangym dependency! 👏 

I had to open [a PR to fragile](https://github.com/justindujardin/fragile/pull/new/fix/plangym_optional) because it was pulling in the `plangym` dependency in the core library (and with it `pillow-simd`)

Here's the PR that implements your gist: https://github.com/justindujardin/mathy/pull/39

**Comment by justindujardin** [comment]
@all-contributors please add @Guillemdb for code

**Comment by justindujardin** [comment]
Thanks for your help @Guillemdb! 

I had some trouble with the ParallelEnv wrapper, so I removed it for now. When I used it I got an error about `FragileEnvironment doesn't have a __call__` method:
```python
def swarm_solve(problem: str, config: SwarmConfig):
    env_callable = lambda: FragileMathyEnv(
        name="mathy_v0", problem=problem, repeat_problem=True
    )
    mathy_env: MathyEnv = env_callable()._env._env.mathy
    if config.use_mp:
        env_callable = ParallelEnv(env_callable=env_callable)
    swarm = Swarm(
        model=lambda env: DiscreteMasked(env=env),
        env=env_callable,
        reward_limit=EnvRewards.WIN,
        n_walkers=config.n_walkers,
        max_epochs=config.max_iters,
        reward_scale=1,
        distance_scale=3,
        distance_function=mathy_dist,
        show_pbar=False,
    )
```

If it's helpful for you I can reproduce the error again, otherwise, I'll just leave the Parallel runner out for the moment since I'm short on time.

I also had the all-contributors bot add you to the contributor list because of your fragile and gist contributions. This means you'll show up on the site and in the GitHub readme:
 - https://github.com/justindujardin/mathy#contributors
 - https://mathy.ai/#contributors

**Comment by Guillemdb** [comment]
@justindujardin this is my fault, I made a mistake in the environment.

It should also be passed as an `env_callable` just like a regular environment with `lambda: ParallelEnv(env_callable=env_callable)`, but I will be adding a `__call__` method to avoid having to create a lambda function. Thanks fot the idea.

> @justindujardin
> 
> I've put up [a pull request](https://github.com/justindujardin/mathy/pull/40) to add @Guillemdb! tada

Thank you man! I really appreciate it. I am sorry I couldn't help you more this weekend.

**Comment by justindujardin** [comment]
Thanks for the mp fix! I restored the functionality in https://github.com/justindujardin/mathy/pull/42 👏
